FROM docker.io/debian:bookworm-slim

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -yq update \
  && apt-get -yq install \
    make \
    git \
    sudo \
    live-build \
    live-boot \
    live-config \
    dirmngr \
    gpgv2 \
    zstd \
    ieee-data \
    libyaml-0-2 \
    python3
