name: Build Installer LiveCD
on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run build.sh
      run: bash ${GITHUB_WORKSPACE}/debian-live/build.sh

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: livecd-output
        path: |
          ${GITHUB_WORKSPACE}/debian-live/output/info/binary.modified_timestamps
          ${GITHUB_WORKSPACE}/debian-live/output/info/build.log
          ${GITHUB_WORKSPACE}/debian-live/output/info/chroot.files
          ${GITHUB_WORKSPACE}/debian-live/output/info/chroot.packages.install
          ${GITHUB_WORKSPACE}/debian-live/output/info/chroot.packages.live
          ${GITHUB_WORKSPACE}/debian-live/output/iso/live-image-amd64.contents
          ${GITHUB_WORKSPACE}/debian-live/output/iso/live-image-amd64.files
          ${GITHUB_WORKSPACE}/debian-live/output/iso/live-image-amd64.hybrid.iso
          ${GITHUB_WORKSPACE}/debian-live/output/iso/live-image-amd64.packages
          ${GITHUB_WORKSPACE}/debian-live/output/boot/chroot/boot"/*
          ${GITHUB_WORKSPACE}/debian-live/output/live/binary/live/filesystem.squashfs
          ${GITHUB_WORKSPACE}/debian-live/output/live/binary/live/filesystem.packages
          ${GITHUB_WORKSPACE}/debian-live/output/live/binary/live/initrd.img"
          ${GITHUB_WORKSPACE}/debian-live/output/live/binary/live/vmlinuz"
