name: Build Installer LiveCD
on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run build.sh
      run: bash ${GITHUB_WORKSPACE}/debian-live/build.sh

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: livecd-output
        path: |
          ./debian-live/output/info/binary.modified_timestamps
          ./debian-live/output/info/build.log
          ./debian-live/output/info/chroot.files
          ./debian-live/output/info/chroot.packages.install
          ./debian-live/output/info/chroot.packages.live
          ./debian-live/output/iso/live-image-amd64.contents
          ./debian-live/output/iso/live-image-amd64.files
          ./debian-live/output/iso/live-image-amd64.hybrid.iso
          ./debian-live/output/iso/live-image-amd64.packages
          ./debian-live/output/boot/chroot/boot"/*
          ./debian-live/output/live/binary/live/filesystem.squashfs
          ./debian-live/output/live/binary/live/filesystem.packages
          ./debian-live/output/live/binary/live/initrd.img"
          ./debian-live/output/live/binary/live/vmlinuz"
