name: Build Installer LiveCD
on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run build.sh
      run: bash ${GITHUB_WORKSPACE}/debian-live/build.sh

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          ${GITHUB_WORKSPACE}/debian-live/output/live-image-amd64.hybrid.iso
